Added 5 tasks
VseslavKasatsky/spbu_2020_c_homeworks pull request #1
Opened 2020-09-18 18:27 UTC by VseslavKasatsky

2020-09-21 09:45 UTC, khodand requested changes

2020-09-21 09:45 UTC, khodand commented on Homework_1/task_3.c
> +	while (1)
Это че?

2020-09-22 16:18 UTC, SpirinEgor requested changes
У тебя не работает автоматическая проверка стайлгайда, надо открыть Actions в репозитории и там включить её

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_1.c
> +	int arr[7][7];
То есть ты вынес в константу, но решил её не использовать?
Лучше, конечно, динамически выделять нужный массив.

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_1.c
> +	int coordinate_x = SIZE / 2, coordinate_y = SIZE / 2, round = 0;
round -- название функции округления, лучше что-то другое придумать

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_1.c
> +	for (;;)
Здесь можно использовать цикл while, а условие у тебя ниже уже есть, его надо адаптировать.
Бесконечный цикл -- плохо

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_2.c
> +	int arr[14];
Константы такие
![image](https://user-images.githubusercontent.com/22539802/93908464-515eff00-fd07-11ea-8499-9ecb235a47f8.png)

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_2.c
> +	int arr[14];
И сделай динамическую память

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_2.c
> +	int arr[14];
И назови array, чего тут сокращать

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_2.c
> +//M-начало, N - конец
Начало и конец чего? Это размеры сегментов, если я правильно понял

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_2.c
> +	}
Можно сделать гораздо быстрее, без вложенных циклов

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_3.c
> +	char search[] = "Blue";
Что за хардкод, строки должны вводиться пользователями

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_3.c
> +	char* p = strstr(str, search);
А если без встроенных функций?

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_4.c
> +		int flag = 1;
Для флагов надо bool использовать

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_5.c
> +	qsort(arr, SIZE, sizeof(int), helper);
Надо решить без сортировки

2020-09-22 16:18 UTC, SpirinEgor commented on Homework_1/task_5.c
> +	int arr[9] = { 4, 7, 1, 4, 9, 2, 3, 9, 7 };
И без захардкоженных массивов

2020-09-22 16:22 UTC, VseslavKasatsky commented on Homework_1/task_1.c
> +	int arr[7][7];
Мой Clion ругается на такое объявление, но может чет поменялось, вернусь к константе. 
Насчет динамического вы в лс сказали, что в первых задачах можно взять статический

2020-09-22 16:27 UTC, SpirinEgor commented on Homework_1/task_1.c
> +	int arr[7][7];
Ну ответ "у меня не работало" не канает, надо разбираться.
Да, можно статический, но через нормальные константы

2020-09-22 16:29 UTC, VseslavKasatsky commented on Homework_1/task_1.c
> +	int arr[7][7];
Нормальные — это какие?

2020-09-22 16:30 UTC, SpirinEgor commented on Homework_1/task_1.c
> +	int arr[7][7];
Ну то есть объявил константу и используешь её

2020-09-22 16:32 UTC, VseslavKasatsky commented on Homework_1/task_3.c
> +	char* p = strstr(str, search);
Это означает, что я должен переписать через посимвольный поиск или...?

2020-09-22 16:40 UTC, SpirinEgor commented on Homework_1/task_3.c
> +	char* p = strstr(str, search);
Ну да, сделать адекватный поиск, он будет посимвольным. А у тебя через одно место, кучу раз запускаешь, \0 расставляешь...

2020-09-22 22:23 UTC, VseslavKasatsky commented
@SpirinEgor исправил

2020-09-24 15:45 UTC, SpirinEgor requested changes
Убери лишние файлы из пр (clang-format)

2020-09-24 15:45 UTC, SpirinEgor commented on CMakeLists.txt
> +        Homework_1/task_1.c Homework_1/task_2.c Homework_1/task_3.c Homework_1/task_4.c Homework_1/task_5.c )
Эти файлы не должны быть частью либы

2020-09-25 10:08 UTC, SpirinEgor approved these changes

2020-09-25 10:08 UTC, merged