20.Б10-мм, Касацкий.В, 4.3
VseslavKasatsky/spbu_2020_c_homeworks pull request #11
Opened 2020-10-14 21:59 UTC by VseslavKasatsky

2020-10-15 18:21 UTC, SpirinEgor requested changes

2020-10-15 18:21 UTC, SpirinEgor commented on Homework_4/task_3.c
> +#define SIZEOFINT 32
Есть встроенная функция sizeof. Вернёт размер. Но только в байтах. Поэтому в этой задаче можно без всяких констант обойтись.

2020-10-15 18:21 UTC, SpirinEgor commented on Homework_4/task_3.c
> +        }
Кажется, что этот switch можно 2 строчками заменить

2020-10-15 18:21 UTC, SpirinEgor commented on Homework_4/task_3.c
> +    bool binaryFirstNumber[SIZEOFINT] = { 0 };
Здесь действительно можно статические массивы использовать. Только сделай это через sizeof

2020-10-15 18:21 UTC, SpirinEgor commented on Homework_4/task_3.c
> +void getBinarySum(bool binaryFirstNumber[], bool binarySecondNumber[], bool binarySum[])
Функции лучше всего разделять хотя бы одной строчкой пустой

2020-10-16 16:44 UTC, SpirinEgor approved these changes

2020-10-16 17:34 UTC, VseslavKasatsky commented
@SpirinEgor Мердж сделаете или самому?

2020-10-17 13:18 UTC, merged