20.Б10-мм, Касацкий.В, 4.1
VseslavKasatsky/spbu_2020_c_homeworks pull request #12
Opened 2020-10-15 23:04 UTC by VseslavKasatsky

2020-10-16 00:13 UTC, VseslavKasatsky commented
Задача не готова, переделаю в течение дня

2020-10-16 15:24 UTC, SpirinEgor requested changes

2020-10-16 15:24 UTC, SpirinEgor commented on Homework_4/task_1.c
> +        string = (char*)realloc(string, size);
В чате обсуждали как надо поступать в таком случае. Лучше всего делать realloc в 2 раза. То если размер массива закончился, то увеличиваем его в 2 раза.

2020-10-16 15:24 UTC, SpirinEgor commented on Homework_4/task_1.c
> +    if (strcmp(subString, "+") == 0) {
Кажется, что в эту функцию достаточно передавать символ (char). Тогда можно будет сравнивать `c == '+'`

2020-10-16 15:24 UTC, SpirinEgor commented on Homework_4/task_1.c
> +        exit(0);
При таком окончании стек не будет очищаться

2020-10-16 15:24 UTC, SpirinEgor commented on library/commonUtils/stack.c
> +bool isEnd(Stack* stack)
Очень странная функция. Что значит isEnd?
Кажется что надо делать isEmpty
Ну и на паре обсудили, что сравнивать надо quantity c нулём.

2020-10-16 17:30 UTC, VseslavKasatsky commented on Homework_4/task_1.c
> +        string = (char*)realloc(string, size);
А не будет ли это использование лишней памяти?

2020-10-16 17:40 UTC, VseslavKasatsky commented on library/commonUtils/stack.c
> +bool isEnd(Stack* stack)
isEnd - это флаг последний ли это элемент, т.е исполнение такое, что есть нулевой элемент 

===
После обработки выражения должен остаться 1 элемент + нулевой. Т.е если после выполнения алгоритма останется больше 1 элемента, то ввели неправильное количество знаков-чисел
    if (getQuantity(stack) != 1)

2020-10-16 18:02 UTC, VseslavKasatsky commented on library/commonUtils/stack.c
> +bool isEnd(Stack* stack)
@SpirinEgor квантити проверяет остались ли какие-то еще элементы в стеке кроме 1 - результата

2020-10-16 18:15 UTC, VseslavKasatsky commented on library/commonUtils/stack.c
> +bool isEnd(Stack* stack)
![image](https://user-images.githubusercontent.com/71323710/96294237-b6e79800-0ff4-11eb-87b7-d28b2eaacbe8.png)
![image](https://user-images.githubusercontent.com/71323710/96294266-c5ce4a80-0ff4-11eb-8892-58774ce35e4f.png)

2020-10-16 18:17 UTC, VseslavKasatsky commented on library/commonUtils/stack.c
> +bool isEnd(Stack* stack)
![image](https://user-images.githubusercontent.com/71323710/96294374-f2826200-0ff4-11eb-84fb-680855bdf5e7.png)
Если квантити = 1, значит элемент 1(именно тот, что содержит результат)

2020-10-17 13:14 UTC, SpirinEgor commented on Homework_4/task_1.c
> +        string = (char*)realloc(string, size);
Тут надо найти золотую середину. Дело в том, что реаллок может копировать весь массив, если не может расширить текущий кусок. Отсюда, если часто увеличивать, то время работы может замедлиться.

2020-10-17 13:16 UTC, SpirinEgor commented on library/commonUtils/stack.c
> +bool isEnd(Stack* stack)
Я понял.
Эта функция нужна для решения задачи, тогда как в либе лежит некая функциональность, которая ничего не знает про задачу. Поэтому странно видеть там какие-то специфичные вещи.

2020-10-17 13:18 UTC, SpirinEgor requested changes

2020-10-17 13:18 UTC, SpirinEgor commented on library/commonUtils/stackPostfix.c
> +    return stack->head->next == NULL;
Но это означает, что в стеке есть хотя бы 1 элемент, а значит он не пустой.
Если тебе нужно отслеживать размер стека, то самым верным решением будет добавить getSize, который возвращает размер стека. Затем где-то вне либы уже сравнивать, что вернулось 1

2020-10-21 10:47 UTC, SpirinEgor approved these changes

2020-10-21 10:48 UTC, merged