20.Б10-мм, Касацкий.В, 5.1
VseslavKasatsky/spbu_2020_c_homeworks pull request #14
Opened 2020-10-25 19:28 UTC by VseslavKasatsky

2020-10-25 19:32 UTC, VseslavKasatsky commented
Я так понимаю, что во 5.2 надо то же, что и для задания 3.2 т.е обертку. 
То тогда получается надо добавить после добавления-удаления балансировку дерева или какой-то тайный смысл AVL-дерева я не понимаю?

2020-10-25 20:15 UTC, SokolovYaroslav commented
> Я так понимаю, что во 5.2 надо то же, что и для задания 3.2 т.е обертку.
> То тогда получается, что надо добавить после добавления-удаления балансировку дерева, или какой-то тайный смысл AVL-дерева я не понимаю?

Я пока сам не разбирался, как лучше всего сделать. Там почему-то этот бонусный балл выглядит как максимальный Я вообще думал оценивать от 0 до 1 в зависимости от того, как хорошо будет переиспользовано решение из 5.1

2020-10-27 08:22 UTC, SokolovYaroslav commented
Ну да, кажется, что достаточно по сути сделать два глобальных переиспользования: переиспользовать старые ноды и переиспользовать всю логику со вставкой-поиском-удалением и поверх этого нацепить перебалансировку

2020-10-27 10:20 UTC, VseslavKasatsky commented
@SokolovYaroslav, когда вы примерно будете проверять? Просто я думаю лучше сначала довести до ума это задание, а потом переиспользовать его в 5.2

2020-10-29 13:25 UTC, SokolovYaroslav requested changes

2020-10-29 13:25 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchTree.c
> +    if (value < node->value) {
Yoda-style condition

2020-10-29 13:25 UTC, SokolovYaroslav commented on CMakeLists.txt
> +target_link_libraries(5.task_1 binarySearchTree)
пустая строка

2020-10-29 13:25 UTC, SokolovYaroslav commented on Homework_5/task_1.c
> +    printf("%d", exists(tree, 7));
Хм, такой формат вывода и задуман? Выглядит оч плохо и не ясно :)

2020-10-29 13:25 UTC, SokolovYaroslav commented on Homework_5/task_1.c
> +    printf("%d", exists(tree, 7));
Ну то есть если посмотреть на код, то норм. Но в идеале хочется, чтобы и так было понятно. Предлагаю что-то поясняющее печатать еще.

2020-10-29 13:25 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchTree.c
> +}
Где-то лишняя закрывающая скобочка при выводе списка.

2020-10-29 13:25 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchTree.c
> +    printf("\n");
Мб объединить всё в один printf?

2020-10-29 13:25 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchTree.c
> +    printf("\n");
В остальных местах с подряд идущими printf тоже предлагаю так сделать

2020-10-29 13:25 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchTree.c
> +    printf("\n");
(Возможно кроме рекурсивных принтов) (но там мб и можно, думать надо)

2020-10-29 13:25 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchTree.c
> +bool changeParent(enum Direction d, BinaryTreeNode* parent, BinarySearchTree* tree, BinaryTreeNode* newNode)
Второй раз слово `direction` стало влом писать?)

2020-10-29 13:25 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchTree.c
> +}
Предлагаю переставить функции местами.
1. Удобнее читать сначала основную функцию, а потом, держа её в голове, читать, что происходит в рекурсивной.
2. Ещё, на мой взгляд, лучше сохранять порядок функций из хэдера. То есть сначала, допустим addValue и все её вспомогателбный функции, потом removeValue и её вспомогательные и тд.

2020-10-29 13:25 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchTree.c
> +bool changeParent(enum Direction d, BinaryTreeNode* parent, BinarySearchTree* tree, BinaryTreeNode* newNode)
А еще у тебя где-то `d` в начале, где `tree`. Путает, когда видишь вызов функции

2020-10-29 13:25 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchTree.c
> +            return true;
Кажется можно все блоки вынести в конец
```
free(node);
return true
```

2020-10-29 13:25 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchTree.c
> +void printSymmetrical(BinarySearchTree* tree)
То есть эта функция называется так, а по сути противоположная называется `printInDescendingRecursive `.
Это странно :) Лучше антонимы подобрать

2020-10-29 14:18 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchTree.h
> +typedef struct BinaryTreeNode BinaryTreeNode;
Зачем кстати это в хэдере?

2020-10-29 17:30 UTC, VseslavKasatsky commented on Homework_5/task_1.c
> +    printf("%d", exists(tree, 7));
Это мы писали на уроке, демонстрирует работу Exists 
Допишу вывод того, что такое 0 и 1

2020-10-29 17:44 UTC, VseslavKasatsky commented on library/commonUtils/binarySearchTree.h
> +typedef struct BinaryTreeNode BinaryTreeNode;
Именно TreeNode ?

2020-10-29 17:45 UTC, VseslavKasatsky commented on library/commonUtils/binarySearchTree.c
> +bool changeParent(enum Direction d, BinaryTreeNode* parent, BinarySearchTree* tree, BinaryTreeNode* newNode)
"А еще у тебя где-то d в начале, где tree. Путает, когда видишь вызов функции"
Немного не понял

2020-10-29 18:13 UTC, VseslavKasatsky commented on library/commonUtils/binarySearchTree.c
> +}
Просто там же зона видимости вроде или как-то так это называется, поэтому если будет сверху основная функция, то она не будет "видеть" рекурсию

2020-11-01 14:16 UTC, VseslavKasatsky commented
@SokolovYaroslav

2020-11-03 12:26 UTC, SokolovYaroslav commented
Можешь, пожалуйста, не резолвить комменты самостоятельно?

2020-11-03 12:33 UTC, SokolovYaroslav requested changes

2020-11-03 12:33 UTC, SokolovYaroslav commented on Homework_5/task_1.c
> +        printf("Enter number");
Пробельчик пропущен тут и дальше

2020-11-03 12:33 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchTree.c
> +void removeTreeRecursive(BinaryTreeNode* node, BinaryTreeNode* parent, enum Direction d, BinarySearchTree* tree)
`direction` и про порядок аргументов здесь тоже применимо

2020-11-05 20:12 UTC, VseslavKasatsky commented
@SokolovYaroslav

2020-11-07 11:00 UTC, SokolovYaroslav requested changes
Ну собственно смотри чат (:

2020-11-08 11:07 UTC, SokolovYaroslav requested changes
` Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
1 8 1 3 1 9 1 4 1 8 1 11 1 1 1 3 1 10 1 -12 1 23 1 5
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
6

 Here's your tree: ( 8 ( 3 ( 1 ( -12 null null ) null )( 4 null ( 5 null null )))( 9 null ( 11 ( 10 null null )( 23 null null ))))
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
2 8 6
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form

 Here's your tree: ( 9 ( 3 ( 1 ( -12 null null ) null )( 4 null ( 5 null null )))( 11 ( 10 null null )( 23 null null )))
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
2 9 6
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form

 Here's your tree: ( 10 ( 3 ( 1 ( -12 null null ) null )( 4 null ( 5 null null )))( 11 null ( 23 null null )))
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
2 10 6
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form

 Here's your tree: ( 11 ( 3 ( 1 ( -12 null null ) null )( 4 null ( 5 null null )))( 23 null null ))
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
2 11 6
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form

 Here's your tree: ( 23 ( 3 ( 1 ( -12 null null ) null )( 4 null ( 5 null null ))) null )
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
2 23 6
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form

 Here's your tree: ( 3 ( 1 ( -12 null null ) null )( 4 null ( 5 null null )))
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
2 3 6
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form

 Here's your tree: ( 4 ( 1 ( -12 null null ) null )( 5 null null ))
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
2 4 6
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form

 Here's your tree: ( 5 ( 1 ( -12 null null ) null ) null )
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
2 5 6
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form

 Here's your tree: ( 1 ( -12 null null ) null )
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
2 1 6
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form

 Here's your tree: ( -12 null null )
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
2 -12 6
Enter number: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form

 Here's your tree: 
 Enter what you want to do
0 - EXIT
1 - add element to tree
2 - remove element from tree
3 - check if a value exists in the tree
4 - print ascending
5 - print descending
6 - print in special form
0
==1701==  [...]

2020-11-08 13:36 UTC, VseslavKasatsky commented
Еще кое-что проверю

2020-11-08 13:59 UTC, VseslavKasatsky commented
Вроде теперь все хорошо

2020-11-13 11:52 UTC, VseslavKasatsky commented
@SokolovYaroslav

2020-11-20 12:08 UTC, SokolovYaroslav requested changes

2020-11-20 12:08 UTC, SokolovYaroslav commented on Homework_5/task_1.c
> +#include "../library/commonUtils/binarySearchAndAvlTree.h"
Что-то я совсем не понял прикола. Ты хочешь сделать только AVL дерево? А что делать, если я обычное захочу использовать?

2020-11-20 12:22 UTC, VseslavKasatsky commented on Homework_5/task_1.c
> +#include "../library/commonUtils/binarySearchAndAvlTree.h"
Использовать функции без

2020-11-20 13:25 UTC, VseslavKasatsky commented on Homework_5/task_1.c
> +#include "../library/commonUtils/binarySearchAndAvlTree.h"
Проще смерджить сразу 5.2 т.к оно на базе 5.1

2020-11-21 22:03 UTC, SokolovYaroslav requested changes
Тогда закрываю этот PR?

2020-11-21 22:03 UTC, closed without merging