20.Б10-мм, Касацкий.В, 6.1
VseslavKasatsky/spbu_2020_c_homeworks pull request #15
Opened 2020-11-01 22:19 UTC by VseslavKasatsky

2020-11-01 22:19 UTC, VseslavKasatsky commented
[text.txt](https://github.com/VseslavKasatsky/spbu_2020_c_homeworks/files/5471870/text.txt)

2020-11-11 13:04 UTC, nbirillo requested changes

2020-11-11 13:04 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +void getMaximumInsertAttempts(HashTable* table)
У тебя название говорит, что ты возвращаешь по идее `maximumInsertAttempts`. Как мне кажется, лучше сделать тогда функцию, которая вернет `maximumInsertAttempts`, а другая уже напечатает (или вернет) элемент(ы) с таким значением (твой второй for)

2020-11-11 13:04 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +    table->elementCount = 0;
У тебя вся эта часть пересекается с тем, что ты делаешь в `createHashTableWithSize`. Может быть это можно вынести с отдельную функцию, чтобы не дублировать код?

2020-11-11 13:04 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +bool pushElement(HashTable* table, char* key, int amount, int insertionAttempts)
Ты ведь в любом случае возвращаешь всегда `true`. Смысл тогда вообще что-то возвращать из этой функции? А как мне удалить элемент из таблицы?

2020-11-11 13:04 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +}
Эта функция не используется + она полностью повторяет первую половину функции `pushElement` за исключением того, что там заполняется значение, а тут принтится. Вообще это хорошая идея вынести в отдельную внутреннюю (недоступную снаружи) функцию эту часть и дальше уже при неуспехе делать вторую часть (ее тоже можно вынести в функцию). А именно как отдельная функция, которая это принтит. я не уверена, что она нужна

2020-11-11 13:04 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +    HashElement** elements = (HashElement**)malloc(10 * sizeof(HashElement*));
ну кажется, что 10 слишком захардкожено. Почему не передавать N, которое будет говорить, сколько нужно вывести из топа?

2020-11-11 13:04 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +        }
Это прям очень коряво выглядит. Еще и внутри цикл, который постоянно останавливается, в котором тоже цикл....

2020-11-11 13:04 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +    }
Ну здесь кажется должно быть что-то: `while (elements[i] != NULL) {}` (читается это явно проще)
У тебя здесь меньше 10 значений может быть выведено только в том случае, если у тебя в принципе в таблице меньше 10 слов. Если же слов в таблице больше 10, то всегда будут выведены 10 значений. В ситуации, когда слов с топовой частотой больше 10, нужно вывести любые 10 из них, но все еще 10 (ну или N собственно, как я написала выше)

2020-11-11 13:04 UTC, nbirillo commented on Homework_6/task_1.c
> +int const LONGESTWORDLENGTH = 27;
Обычно, если используется такая нотация, то слова внутри разделяют нижним подчеркиванием, чтобы это читалось
Но все должно быть динамически и длина каждого слова должна вычисляться тоже динамически

2020-11-11 13:04 UTC, nbirillo commented on Homework_6/task_1.c
> +    bool flag = getWord(word, file);
Опять странное имя у флага - называй так, зачем он нужен) в данном случае отслеживать, кончился ли файл или нет. а то приходится лезть внутрь функции, чтобы понимать, что происходит

2020-11-11 13:04 UTC, nbirillo commented on Homework_6/task_1.c
> +    while (flag) {
Ну и можно сделать цикл что-то типа: пока файл не кончился, считывай слово и добавляй в таблицу

2020-11-11 13:04 UTC, nbirillo commented on Homework_6/task_1.c
> +        pushElement(table, word, 1, 1);
Кажется, что хочется вызывать просто `pushElement(table, word, 1)`, а остальное должно быть скрыто в реализации

2020-11-11 13:04 UTC, nbirillo commented on Homework_6/task_1.c
> +    getMaximumInsertAttempts(table);
Ну вот тут опять же я уже писала выше - лучше разделить по функциям - получить и напечатать или сделать функцию, которая печатает и говорит об этом в названии, а то сейчас кажется, что ты получаешь это значение в никуда из названия

2020-11-11 13:04 UTC, nbirillo commented on Homework_6/task_1.c
> +    fclose(file);
Вообще я бы сделала отдельную функцию для считывания данных и отдельную для вывода всей статистики

2020-11-11 13:04 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
Еще момент - у тебя выводится:
Total added words: 192
Их действительно 192, если бить по пробелам. Но в условии прописано, что слово — непрерывная последовательность из букв, так что Napoleon—his - это два слова, а не одно. У тебя две такие ситуации: Napoleon—his и hero—but, тем самым слов 194

2020-11-11 13:04 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
Теперь давай на примере попроще:
Возьмем такой текст:
`Prince Andrew prince-Andrew Andrew.`
Мы не должны учитывать регистр и знаки перепинания
таким образом, у нас тут всего два слова - prince и andrew, которые будут добавлены, а также уникальных слов тоже 2, топ слов будет состоять тоже из двух
вот что выводится у тебя:
```
Average number of attends: 1.000000
The word w/ most attempts <andrew> - 1
The word w/ most attempts <princeandrew> - 1
The word w/ most attempts <prince> - 1
Load factor: 0.375000
Total added words: 3
Number of unique words: 3
Number of empty table cells: 5

 1. andrew - repeated 1 times
 2. princeandrew - repeated 1 times
 3. prince - repeated 1 times
```

2020-11-11 13:04 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
Если взять пустой файл, то `Average number of attends: nan`

2020-11-11 13:04 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
Возьмем пример: `Prince prince-a`
Твой вывод:
```
Average number of attends: 1.000000
The word w/ most attempts <prince> - 1
Load factor: 0.500000
Total added words: 1
Number of unique words: 1
Number of empty table cells: 1

 1. prince - repeated 1 times
```

Очевидно, что это неверно

2020-11-11 13:04 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
Более того, если запускать программу на твоем примере, то Valgring ругается
![image](https://user-images.githubusercontent.com/8993915/98813362-19398a00-2435-11eb-868c-803e857161f1.png)

2020-11-11 13:04 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
А если еще такой взять пример:
```
one two three four five six seven eight nine ten eleven twelve
```
то последнее слово не учитывается
```
Average number of attends: 1.000000
The word w/ most attempts <six> - 1
The word w/ most attempts <ten> - 1
The word w/ most attempts <eight> - 1
The word w/ most attempts <one> - 1
The word w/ most attempts <five> - 1
The word w/ most attempts <eleven> - 1
The word w/ most attempts <three> - 1
The word w/ most attempts <four> - 1
The word w/ most attempts <nine> - 1
The word w/ most attempts <two> - 1
The word w/ most attempts <seven> - 1
Load factor: 0.687500
Total added words: 11
Number of unique words: 11
Number of empty table cells: 5

 1. six - repeated 1 times
 2. ten - repeated 1 times
 3. eight - repeated 1 times
 4. one - repeated 1 times
 5. five - repeated 1 times
 6. eleven - repeated 1 times
 7. three - repeated 1 times
 8. four - repeated 1 times
 9. nine - repeated 1 times
 10. two - repeated 1 times
```

2020-11-11 13:09 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
Файл должен оканчиваться пробелом (
Не знаю как тут тогда лучше адаптировать, чтобы без пробела в конце считало символ

2020-11-11 13:12 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +bool pushElement(HashTable* table, char* key, int amount, int insertionAttempts)
Вроде же для реализации "проблемы" функция удаления не нужна, хотя сделать можно.

2020-11-11 13:13 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +}
Егор попросил ее сделать, хотя задача этого не требует. 
ок, удалю.

2020-11-11 13:13 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
Он никому ничего не должен :) Нужно просто верно обработать конец файла, это все гуглится

2020-11-11 13:14 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +    HashElement** elements = (HashElement**)malloc(10 * sizeof(HashElement*));
В условии задачи - топ 10
Некоторое время назад и такого условия не было. Требовалось только 1 слово. Внесли правки в условие, теперь видимо так...

2020-11-11 13:14 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +    HashElement** elements = (HashElement**)malloc(10 * sizeof(HashElement*));
Хотя можно и топ N

2020-11-11 13:15 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +bool pushElement(HashTable* table, char* key, int amount, int insertionAttempts)
Реализовать структуру данных hash-таблица (разрешение коллизий методом открытой адресации, квадратичная последовательность проб).
Так звучит первая часть задания) обычно в структуру данных ты можешь не только вставлять элементы, но и удалять

2020-11-11 13:16 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +}
ты можешь ее вызывать внутри другой, как я описала выше и еще в дополнение принтить тогда, раз это нужно для отладочной информации

2020-11-11 13:17 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +    HashElement** elements = (HashElement**)malloc(10 * sizeof(HashElement*));
ну вот видишь - чтобы не было проблем, можно сделать N и тогда реализация не будет зависеть от условия) использовать чисто цифры типа 10 не очень хорошо

2020-11-11 13:17 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int const LONGESTWORDLENGTH = 27;
Можно. Хотя постоянный реллокейт и увеличение памяти в 2 раза, хз. Ок

2020-11-11 13:19 UTC, nbirillo commented on Homework_6/task_1.c
> +int const LONGESTWORDLENGTH = 27;
ну а что будет, если я введу длинное слово? больше 27 символов? или если у меня весь текст состоит из слов по 1 символу, то у меня всегда будет куча лишней памяти выделяться?

2020-11-11 13:19 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +bool pushElement(HashTable* table, char* key, int amount, int insertionAttempts)
Справедливо

2020-11-11 13:19 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +}
Тогда лучше не нужно)

2020-11-11 13:20 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int const LONGESTWORDLENGTH = 27;
27 - самое большое слово в Английском, но справедливо. Сделаю

2020-11-11 13:21 UTC, nbirillo commented on Homework_6/task_1.c
> +int const LONGESTWORDLENGTH = 27;
Ну допустим я возьму немецкий :)))))) (без доп символов, которых нет в англ языке)

2020-11-11 13:26 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +        }
А можно намек на то, как лучше сделать?)
Не знаю насколько это будет лучше, но можно найти 1 значение, добавить его в топ, а потом с этого места сканировать таблицу и при нахождении непустого значения такой же алгоритм как здесь, только для читаемости можно while

2020-11-11 13:28 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +    getMaximumInsertAttempts(table);
т.е например
1 функция возвращает int - количество попыток
другая функция печатает это значение

2020-11-11 13:31 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
А на вашем примере Valgrind не ругается?

2020-11-11 13:36 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +    getMaximumInsertAttempts(table);
так?

2020-11-11 13:57 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +        }
https://stackoverflow.com/questions/185697/the-most-efficient-way-to-find-top-k-frequent-words-in-a-big-word-sequence/22341665#22341665

Первые два пункта можно поддерживать внутри таблицы, то есть в любой момент времени при желании можно сделать так, чтобы можно было вернуть max freq (делается очень просто, подумай), ну а потом пройтись по бакетам и сделать нужное (как в п 3 например). В таком случае будет сильно читабельней

2020-11-11 13:58 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +        }
я бы делала так)

2020-11-11 14:01 UTC, nbirillo commented on Homework_6/task_1.c
> +    getMaximumInsertAttempts(table);
либо 2 функции - одна ищет это число, да, а вторая принтит все с этим числом. Либо поменять эту функцию на print что-то там, чтобы было понятно, что она принтит значения, а не просто что-то ищет в никуда

2020-11-11 14:02 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
да на всех ругается) ну кроме пустого файла

2020-11-11 15:42 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
Случаем не в функции expand?)

2020-11-11 16:48 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
а может ты себе Valgrind поставишь или его аналог?)

2020-11-11 17:00 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +        }
А вот вопрос, при удалении 1 элемента мы же должны пробегать полностью всю таблицу и искать 2 максимум

2020-11-11 17:04 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
Осталось всего до конца сема без него дотянуть ((

2020-11-11 17:12 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
Тогда играй в предсказателя :)

2020-11-11 17:19 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
Жестоко (

2020-11-11 17:50 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +        }
![image](https://user-images.githubusercontent.com/71323710/98845877-62063880-245f-11eb-8a5c-60a3be4970ee.png)
А массив чего делать? Ну т.е можно сделать массив строк, тогда если по этому индексу уже есть слово, то к строке этой прирастить новое слово. Или как?

2020-11-12 10:28 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +        }
ну тебе необязательно делать прямо ровно также. Почитай про устройство хэш-таблиц в интернете и попробуй сделать, так как ты должен научиться делать это сам, а не реализовывать готовый алгоритм. Если во второй попытке не станет сильно лучше, то посмотрим (но должно быть понятно, что ты хотя бы пытался)

2020-11-12 18:38 UTC, VseslavKasatsky commented
Утечек должно было стать меньше, но я не знаю как можно удалить последнюю утечку

2020-11-12 20:44 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
@nbirillo Visual studio тоже оказывается хорошо показывает утечки :)

2020-11-13 08:35 UTC, nbirillo requested changes
Стало сильно лучше, отправила тебе логи Valgrind-а, чтобы ты смог понять, куда смотреть, чтобы починить утечки

2020-11-13 08:35 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +            while (elementsIndex[index] > -1 && table->hashTable[i]->amount < table->hashTable[elementsIndex[index]]->amount && index < numberOfRepetitiveWords) {
Можно условие в функцию вынести, так будет понятнее читаться. Но а вообще стало сильно лучше выглядеть по сравнению с тем, что было

2020-11-13 08:35 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
Может быть тебе так проще будет? Попробуй починить)
![image](https://user-images.githubusercontent.com/8993915/99044997-b4e80900-25a1-11eb-8f5e-8fc5b729b052.png)
Файл 
```
one two three four five six seven eight nine ten eleven twelve
```
Количество слов в топе - 5
а вот на  таком файле  например
```
one one-two
```
и Количество слов в топе - 5 не ругается

2020-11-13 08:35 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +bool removeElement(HashTable* table, char* key)
А сделай так, чтобы я могла вызывать из main ее?

2020-11-13 08:35 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
В main после 
```
int numberOfRepetitiveWords = 0; 
scanf("%d", &numberOfRepetitiveWords);
```
вызываю 
```
removeElement(table, "1");
```
на файле
```
Prince Andrew prince-Andrew Andrew.
```
топ слов 5
получаю
![image](https://user-images.githubusercontent.com/8993915/99045921-19579800-25a3-11eb-86fc-72bd18000550.png)
![image](https://user-images.githubusercontent.com/8993915/99045931-1ceb1f00-25a3-11eb-8dd9-e8326b41c34f.png)

При этом если вызвать
```
removeElement(table, "prince");
```
то будет норм (в плане он отработает, но valgrind все равно будет ругаться):
![image](https://user-images.githubusercontent.com/8993915/99046273-9551e000-25a3-11eb-83e7-e836d46071b8.png)

2020-11-13 08:35 UTC, nbirillo commented on Homework_6/task_1.c
> +    printLoadFactor(table);
Может быть сделаешь тут отдельную функцию, которая печататает всю статистику?

2020-11-13 11:20 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
remove пофиксил, там теперь общая функция delete, которая удаляет char'овский массив тоже.
А так 
![image](https://user-images.githubusercontent.com/71323710/99067118-3304d980-25bb-11eb-9ae1-d70fe9ae6df0.png)
А так больше утечек вроде как нет, ну мне так почему-то показывает. ucrt... - вроде что-то системное. 

Вот у вас на скринах валгринда пишет про функцию LostOfMostCommnoWords, но там же вроде единственный массив - массив int'ов, который очищается (

2020-11-13 11:23 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
Хотя да, почему-то он отображает не все утечки(

2020-11-13 11:26 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
![image](https://user-images.githubusercontent.com/71323710/99067630-187f3000-25bc-11eb-8326-cd4e027fce17.png)
Вот, что хранится в утечке ucrtbased, ну да, вроде системное

2020-11-13 11:42 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
Точно ли в этой функции тогда утечка?

2020-11-13 12:36 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
ну давай по-другому - там же написано, что ошибка в чтении: Invalid read

Если на том же примере (one two three four five six seven eight nine ten eleven twelve) и 5 слов ты запустишь, но при это закоментишь строчки чтения
```
    while (elementsIndex[i] != -1 && i < numberOfRepetitiveWords) {
        printf("\n %d. %s - repeated %d times", i + 1, table->hashTable[elementsIndex[i]]->key, table->hashTable[elementsIndex[i]]->amount);
        ++i;
    }
```
то ошибка пропадет

а теперь делай выводы и ищи ошибку, что тут может быть не так)

2020-11-13 12:49 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
Нашел, break; использовать можно?)

2020-11-13 12:52 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
Хотя, чисто теоретически (т.к у меня эту ошибку не видит)
    while ( i < numberOfRepetitiveWords && elementsIndex[i] != -1 )
то последовательно проверяются условия => 2 наверное не проверит => не приведет к ошибке?

2020-11-13 12:54 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
все так, ты знаешь почему так работает?

2020-11-13 13:00 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
Могу предположить, что люди, создавшие язык, поняли, что если 1 вернуло 0, то 2 проверять не нужно т.к это их && 
Хотя может есть глубокий смысол?

2020-11-13 13:07 UTC, nbirillo commented on Homework_6/task_1.c
> +int main()
ага, так работает во многих языках. Суть в том, что ты можешь очень красиво писать какие-то условия + экономить например время вычислений и тд. Если уже можно сказать результат, то дальнейшие выражения вычисляться не будет (так работает не только с and, но и с or например и тд). Поэтому когда ты пишешь код с такими условиями, то лучше вперед ставить наименее затратные условия по вычислениям или же как тут необходимо сначала проверить, что индекс валидный и лишь потом обращаться по нему, иначе будет ошибка чтения. но в целом ты молодец, что догадался сам

2020-11-13 13:10 UTC, VseslavKasatsky commented on Homework_6/task_1.c
> +int main()
Спасибо)

2020-11-14 16:12 UTC, VseslavKasatsky commented
@nbirillo можете пожалуйста ревью сделать 👉🏻👈🏻

2020-11-15 06:59 UTC, nbirillo requested changes
В остальном нормально (без допа пока что)

2020-11-15 06:59 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
Ой, а зачем ты прямо все объединил? подразумевалось, что будет функция, которая вызывает другие функции, которые уже были. Поправь, пожалуйста

2020-11-15 08:42 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
А, не так понял...
Что означает без допа? Без доп.баллов или правок?

2020-11-15 09:05 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
без доп баллов - ну суть в том, чтобы ты мог без проблем передавать свою функцию, а не менял реализацию

2020-11-15 09:07 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
Так, и что теперь получается делать? Дедлайн сегодня(
Но получается надо пользователю дать "право выбора" какое пробирование и какой алгоритм хеширования?

2020-11-15 09:08 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
ну представь, что я использую твою реализацию таблицы, но я хочу использовать другие функции хэширования и пробирования. Я должна исходники менять для этого?

2020-11-15 09:13 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
Ну т.е в си-шнике пользователь сам пишет функцию хеширования-пробирования, а в нее надо каким-то образом передать данные из библиотеки?

2020-11-15 09:18 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
ну например так. хочется, чтобы сценарий был такой: я подключаю твою хэш таблицу и могу не меняя исходников делать таблицу с моими функциями хэширования и пробирования - вот за это + 2 балла тогда

2020-11-15 09:26 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
Ну тогда придется добавить функции, которые return bucketCount, и тд, а также функцию, которая просто забирает число из сишника и передает его хешу или индексу

2020-11-15 09:29 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
ну там много вариантов, как это можно сделать) желательно, чтобы было не костыльно)

2020-11-15 09:44 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
Я вот раньше не сталкивался, а можно вызывать внутри функции в библиотеке функцию из main'a ? Наверное, нет...

2020-11-15 09:54 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
Нет, нельзя))

2020-11-15 10:19 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
Ну вроде сделал :)

2020-11-15 10:20 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
Только если названия поменять

2020-11-15 10:31 UTC, VseslavKasatsky commented on library/commonUtils/hashTable.c
> +void printTableStatistic(HashTable* table)
Можно, конечно, удалить getHash и getIndex и везде поменять на getHashOutside и getIndexOutside, но надо ли?

2020-11-15 10:46 UTC, VseslavKasatsky commented
Можно, конечно, удалить getHash и getIndex и везде поменять на getHashOutside и getIndexOutside, но надо ли?

2020-11-15 17:04 UTC, VseslavKasatsky commented
Вроде то, что надо было

2020-11-15 18:14 UTC, nbirillo requested changes
В остальном все ок, могу зачесть пока без допа, как поправишь эти мелкие штуки. Над допом думай пока что

2020-11-15 18:14 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +    ;
А что тут за странные точки с запятой?

2020-11-15 18:14 UTC, nbirillo commented on library/commonUtils/hashTable.c
> +        ;
А что тут за странные точки с запятой?

2020-11-15 20:52 UTC, VseslavKasatsky commented
Спасибо, благодаря вам узнал, что так можно делать)

2020-11-19 11:34 UTC, nbirillo approved these changes
Отлично, молодец!)

2020-11-19 11:34 UTC, merged