20.Б10-мм, Касацкий.В, 5.2
VseslavKasatsky/spbu_2020_c_homeworks pull request #17
Opened 2020-11-07 22:10 UTC by VseslavKasatsky

2020-11-08 11:44 UTC, SokolovYaroslav requested changes
Добавил последовательно 1 2 3 4 5 6 7 8 9 10
Удалял последовательно 1 2 3 4 5 6 7 8 9 10
На последнем удалении сломалось

2020-11-20 12:10 UTC, SokolovYaroslav requested changes

2020-11-20 12:10 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchAndAvlTree.c
> +}
То есть в теории я могу сначала работать с деревом как с BST, а потом как с AVL и всё сломается?

2020-11-20 12:10 UTC, SokolovYaroslav commented on library/commonUtils/binarySearchAndAvlTree.h
> +bool removeValueFromBST(BinarySearchTree* tree, int value);
Ну это очень странный интерфейс в общем :)
Надо как-то это разделять. Это всё-таки разные структуры

2020-11-20 12:23 UTC, VseslavKasatsky commented on library/commonUtils/binarySearchAndAvlTree.c
> +}
Ну пользователь может выбрать какое дерево строить. Тип переиспользование. Он может сделать avl, тогда использовать добавление-удаление avl, а может обычное

2020-11-20 17:42 UTC, VseslavKasatsky commented
@SokolovYaroslav что-то подобное?

2020-11-21 11:24 UTC, SokolovYaroslav commented
Я до сих пор вижу один общий .h

2020-11-21 19:20 UTC, VseslavKasatsky commented
@SokolovYaroslav что-то подобное?

2020-11-21 22:02 UTC, SokolovYaroslav approved these changes
Что-то подобное, да

2020-11-21 22:02 UTC, merged