20.Б10-мм, Касацкий.В, 7.1
VseslavKasatsky/spbu_2020_c_homeworks pull request #18
Opened 2020-11-08 17:44 UTC by VseslavKasatsky

2020-11-09 13:25 UTC, VseslavKasatsky commented
другое решение

2020-11-24 10:39 UTC, SpirinEgor requested changes

2020-11-24 10:39 UTC, SpirinEgor commented on Homework_7/task_1.c
> +    for (int i = 0; i < numberOfStudents; ++i) {
Если ты используешь константу с числом вариантов, то её уместно тут использовать.
У тебя первые `VARIANTSNUMBER` вариантов оригиналы, для них считывать не надо

2020-11-24 10:39 UTC, SpirinEgor commented on Homework_7/task_1.c
> +            students[i] = createEdge(0, studentNumber, 1, true);
Похоже на костыль, "если не сделал работу, то как будто списал с 0".
Кажется, что не надо просто делать такие рёбра, а потом проверять достижимость

2020-11-27 10:48 UTC, SpirinEgor approved these changes

2020-11-27 10:48 UTC, SpirinEgor commented on .clang-format
> +AlignOperands:   false
Этого файла не должно тут быть

2020-11-27 10:48 UTC, merged