20.Б10-мм, Касацкий.В, 2.3
VseslavKasatsky/spbu_2020_c_homeworks pull request #2
Opened 2020-09-20 11:15 UTC by VseslavKasatsky

2020-09-22 18:55 UTC, nbirillo requested changes
Добавь, пожалуйста, автоматическую проверку стайлгайда

2020-09-22 18:55 UTC, nbirillo commented on Homework_2/2.task_3.c
> +	int arr[11] = { 5, 0, 1, 5, 2, 0, 6, 0, 3, 7, 0 };
Сделал константу `N` и все равно используешь значение? + без захардкоженных массивов, пожалуйста
И экономия 2 букв не сильно хороша - используй array

2020-09-22 18:55 UTC, nbirillo commented on Homework_2/2.task_3.c
> +	int i = 0;
Зачем нужна эта переменная? Вернее, если тут будет так, то в следующей строке можно просто `for (; i < N; i++)` - не инициализировать еще раз. Получится вот так:
```
int i = 0;
for (; i < N; i++)
```

Но более хороший вариант - `for (int i = 0; i < N; ++i)` и удалить эту строчку вовсе

2020-09-22 18:55 UTC, nbirillo commented on Homework_2/2.task_3.c
> +	for (i = 0; i < N; i++)
Знаешь в чем разница` i++` и `++i`? Я бы для одних и тех же целей рекомендовала использовать одинаковую нотацию. Не очень понятно, почему тут ты используешь ` i++`, а ниже `++i`. Можно почитать например [тут](https://medium.com/better-programming/stop-using-i-in-your-loops-1f906520d548) про разницу.

2020-09-22 18:55 UTC, nbirillo commented on Homework_2/2.task_3.c
> +		}
Нужно сделать за линейное время

2020-09-23 16:21 UTC, nbirillo requested changes

2020-09-23 16:21 UTC, nbirillo commented on Homework_2/2.task_3.c
> +            array[counter_end] = vault;
А можешь сделать swap без дополнительной переменной?

2020-09-23 16:21 UTC, nbirillo commented on Homework_2/2.task_3.c
> +    }
![image](https://user-images.githubusercontent.com/8993915/94040585-ceef4180-fdd1-11ea-878f-7c39f6d47b09.png)
Тестировал на массиве из нулей?

2020-09-23 16:44 UTC, VseslavKasatsky commented on Homework_2/2.task_3.c
> +    }
Не могу ответить в другом П.Р. 
Егор кидал просто ссылку https://webkit.org/code-style-guidelines/ на вебкит
Я может немного не понимаю как это работает, но по этому стайлгайду clion форматирует и тесты github'a принимают. Наверное я ошибочно понимаю работу тестов git'a

2020-09-23 16:53 UTC, nbirillo commented on Homework_2/2.task_3.c
> +    }
Должно работать без файлика этого, если настроить все верно, как объяснял Егор :)

2020-09-23 16:56 UTC, VseslavKasatsky commented on Homework_2/2.task_3.c
> +    }
:(

2020-09-23 16:58 UTC, nbirillo commented
После вмерживания в мастер у тебя будут появляться конфликты. Перед ререквестом исправляй их, пожалуста. Плюс не во всех ПР избавился от того файлика со стайлгайдом

2020-09-23 17:27 UTC, nbirillo approved these changes
Отлично, зачтено!

2020-09-23 17:27 UTC, merged