20.Б10-мм, Касацкий.В, 2.4
VseslavKasatsky/spbu_2020_c_homeworks pull request #3
Opened 2020-09-20 12:38 UTC by VseslavKasatsky

added task 2.4
updated CMakeLists.txt for task 2.4

2020-09-22 19:41 UTC, nbirillo requested changes
Добавь, пожалуйста, автоматическую проверку стайлгайда

2020-09-22 19:41 UTC, nbirillo commented on Homework_2/2.task_4.c
> +	scanf_s("%d", &number);
У тебя Windows? Этот код будет работать только там - аналогичный пример описан [тут](https://stackoverflow.com/questions/57915149/using-c11-standard-with-clang-for-use-of-strcpy-s). Дело в том, что функция `scanf_s` действительно есть в стандарте С11, но она была добавлена только в майкрософтовский компилятор. Поэтому при попытке запустить это у себя (у меня мак, на линуксе будет аналогично), я получаю следующую ошибку:
```
Undefined symbols for architecture x86_64:
  "_scanf_s", referenced from:
      _main in 2.task_4.c.o
ld: symbol(s) not found for architecture x86_64
```
Так как Си - это все же больше про unix-системы, то я попрошу переписать этот код, чтобы он запускался не только под Windows. Да и вообще лучше писать код, который запускается под любой системой (и уж точно запускается по unix-системами в первую очередь, а не наоборот)

Также программа должна быть понятной пользователю - например, нужно написать, чтобы пользователь ввел число, тогда при запуске программы не будет вопросов, почему ничего не происходит до ввода.

2020-09-22 19:41 UTC, nbirillo commented on Homework_2/2.task_4.c
> +	int number = 0, arr[10] = { 0 }, j;
Что за магическое значение 10? Дальше оно же используется в циклах.
Объявляешь переменную `j` без инициализации - так делать плохо, убираем
Используй `array` вместо `arr`

2020-09-22 19:41 UTC, nbirillo commented on Homework_2/2.task_4.c
> +	number = 0;
Ты же используешь деление нацело в предыдущей строчке, то есть на последнем шаге у тебя будет что-то типа 1...9 / 10 = 0
У тебя автоматически значение превратится в ноль

2020-09-22 19:41 UTC, nbirillo commented on Homework_2/2.task_4.c
> +		for (j = 1; j < 10; j++)
А чем тебе `i` не понравилась? Идем в домашку 2.3 и читаем про объявление переменной внутри `for` и про разницу` i++` и `++i`.

Также, когда видишь такой цикл, хочется думать, что он и будет выполняться все 10 (N) раз. Но в твоем случае ты просто ищешь первый ненулевой элемент. и останавливаешь цикл. Подумай, как можно сделать это более элегантно, например через while и number в условии (ведь у тебя изначально number 0, а в процессе меняется) (но возможно у тебя вообще поменяется подход, когда ты прочтешь последний коммент)

2020-09-22 19:41 UTC, nbirillo commented on Homework_2/2.task_4.c
> +	if (arr[0] != 0)
Добавь комментарии к коду - тебе самому будет проще понять, что происходит спустя какое-то время. Например здесь что-то типа: Учесть случай, если число содержит ноль

2020-09-22 19:41 UTC, nbirillo commented on Homework_2/2.task_4.c
> +		}
Протестируй на таком вводе: `8983456788432121` или таком `44455555555333444532`. Ты уверен в своем алгоритме? :)

2020-09-23 06:47 UTC, VseslavKasatsky commented on Homework_2/2.task_4.c
> +	int number = 0, arr[10] = { 0 }, j;
@nbirillo 10 - сколько всего цифр существует 0,1,2,3,4...В ячейках массива хранится количество их в числе

2020-09-23 07:47 UTC, VseslavKasatsky commented on Homework_2/2.task_4.c
> +		}
это int ограничение дает, поэтому поищу возможный другой вариант

2020-09-23 07:51 UTC, nbirillo commented on Homework_2/2.task_4.c
> +	int number = 0, arr[10] = { 0 }, j;
я понимаю :) но лучше использовать константу, а не все время писать 10

2020-09-23 07:51 UTC, nbirillo commented on Homework_2/2.task_4.c
> +		}
есть например long)

2020-09-23 08:18 UTC, VseslavKasatsky commented on Homework_2/2.task_4.c
> +		}
А вот вопрос касающийся объявления переменных
Получается даже если несколько циклов, то лучше инициализировать переменную "Счетчик" в каждом цикле

2020-09-23 08:39 UTC, nbirillo commented on Homework_2/2.task_4.c
> +		}
Ты это итак делаешь, просто у тебя до этого сначала валяется бесхозная переменная, а потом ты каждый раз ее обнуляешь. Представь, что у тебя программа не в 50 строчек, а в хотя бы 200 и у тебя переменная из цикла обявлена где-то в начале программы. Кажется, что ты потеряешься, когда будешь пытаться ее искать. Обычно это нормальная практика, если ты делаешь `int i = 0` прямо внутри цикла. Есть такая штука, как [область видимости](https://prog-cpp.ru/c-objects-namespace/) - это когда ты объявил переменную внутри блока и после выхода из блока она удаляется и значение очищается. А в твоем случае переменная будет существовать от начала до конца + возрастает вероятность ошибки просто потому что можно забыть ее обнулить\удалить и тд

2020-09-23 16:13 UTC, nbirillo requested changes

2020-09-23 16:13 UTC, nbirillo commented on Homework_2/2.task_4.c
> +    scanf("%I64d", &number);
У меня твой код не работает с такими `%I64d` параметрами тут и в 31 строке - просто загугли. Так работает только под Windows. Либо делай определение системы и используй разные параметры, либо устанавливай линукс :) Но твой код должен работать под unix системами точно. Также опять нет комменатрия для пользователя, что ему надо ввести

2020-09-23 16:13 UTC, nbirillo commented on Homework_2/2.task_4.c
> +    for (int i = 0; i < DIGIT_AMOUNT; i++) {
`i++` -> `++i`

2020-09-23 16:13 UTC, nbirillo commented on Homework_2/2.task_4.c
> +        number = number / 10;
Давай стараться сокращать код, если это возможно - `number = number / 10;` -> `number /= 10;`

2020-09-23 17:28 UTC, nbirillo commented
Конфликты

2020-09-23 17:46 UTC, nbirillo requested changes

2020-09-23 17:46 UTC, nbirillo commented on Homework_2/2.task_4.c
> +            }
Проверь на числе, где есть 0, например на 54332000 - зациклится навечно

2020-09-23 18:00 UTC, VseslavKasatsky commented on Homework_2/2.task_4.c
> +            }
@nbirillo извините)
i++ должно стоять вне if'а 
Исправил

2020-09-23 19:08 UTC, nbirillo requested changes

2020-09-23 19:08 UTC, nbirillo commented on Homework_2/2.task_4.c
> +    long long int number = 0;
Последнее косметическое изменение перед тем, как принять задачу - давай разделим большое полотно кода на несколько функций для повышения читабельности кода - например тут очень хорошо выделяется считывание данных, заполнение массива array (который лучше бы переименовать на что-то более созвучное тому, что там хранится - там хранятся частоты для каждой цифры, следовательно можно что-то типа digit_freq или что-то похожее), действия, которые выполняются, если первая цифра это ноль и собственно последняя - которая получает новое значение. Так все станет гораздо красивее + твой код будет более переиспользуемым. Возможно можно поделить как-то по-другому. Подумай, пожалуйста и поправь + очень хочется, чтобы в задаче, которую я еще не смотрела (2.2 кажется) этот момент тоже был учтен.

2020-09-23 20:50 UTC, VseslavKasatsky commented on Homework_2/2.task_4.c
> +    long long int number = 0;
Хорошо, 2 задачу тоже подразобью на функции, оставлю комментарии. 
Извините, что вам до этого приходилось разбираться без комментариев :(

2020-09-24 07:55 UTC, nbirillo approved these changes
Отлично, зачтено!

2020-09-24 07:55 UTC, nbirillo commented on Homework_2/2.task_4.c
> +    output_smallest_number(number, link_digit_freq);
Можно было обойтись без лишней переменной и скастовать на ходу:
 ```
 input_digit_frequency(number, (int *) &digit_freq);
 output_smallest_number(number, (int *) &digit_freq);
```
Сейчас засчитаю (так как вы еще мало такое проходили), но в будущем лучше избегать использования лишних переменных, если можно обойтись без них

2020-09-24 07:55 UTC, merged