20.Б10-мм, Касацкий В., 2.2
VseslavKasatsky/spbu_2020_c_homeworks pull request #5
Opened 2020-09-20 21:27 UTC by VseslavKasatsky

2020-09-24 12:30 UTC, VseslavKasatsky commented
Поправлю лишнию переменную link 
И забыл Константу проставить вместо '4' 
P.S. Это если вы начали проверку, а этих изменений ещё не будет

2020-09-24 14:44 UTC, VseslavKasatsky commented
Теперь можно проверять, @nbirillo

2020-09-24 16:03 UTC, nbirillo requested changes

2020-09-24 16:03 UTC, nbirillo commented on Homework_2/task_2.c
> +int main()
Кажется так быть не должно))))))
![image](https://user-images.githubusercontent.com/8993915/94167711-7e411c80-fe95-11ea-9329-0a5c581294ef.png)

2020-09-24 16:03 UTC, nbirillo commented on Homework_2/task_2.c
> +    int random_number_array[DIGITAL_RANGE];
Пора переходить на динамические массивы - пусть `DIGITAL_RANGE` будет введено с клавиатуры и ты будешь создавать динамический массив

2020-09-24 16:03 UTC, nbirillo commented on Homework_2/task_2.c
> +    bool flag = 1;
Если используешь тип `bool`, то используй уж тогда `true` и `false` (везде ниже аналогично). Также давай избавляться от непонятный имен - что за `flag`? Назови его что-то типа `isBlaBla` или как-нибудь еще. Чтобы было понятно, за что он отвечает. Правило простое - закрыл остальную часть кода и по названию можешь понять, зачем нужна эта переменная - значит все делаешь верно

2020-09-24 16:03 UTC, nbirillo commented on Homework_2/task_2.c
> +void generating_random_number(int* random_number_array)
Название (уже писала про это) - давай стараться начинать название с глагола, если прямое назначение функции _что-то_ сделать - например СГЕНЕРИРОВАТЬ, ЗАПОЛНИТЬ. Что-то типа `fill_with_random_numbers`. Тут можно не включать в название `array` - ну просто потому что он в аргументе и это итак понятно. Да и просто можно назвать `numbers` или `random_numbers` например. Старайся сокращать, где это возможно

2020-09-24 16:03 UTC, nbirillo commented on Homework_2/task_2.c
> +        }
Что вообще за сложная логика? Зачем так сложно генерировать массив рандомных чисел?

2020-09-24 16:03 UTC, nbirillo commented on Homework_2/task_2.c
> +    bool flag = 1;
`1` замени на `true`, поменяй название с `flag` на что-то более говорящее

2020-09-24 16:03 UTC, nbirillo commented on Homework_2/task_2.c
> +        }
Вынеси это в отдельную функцию

2020-09-24 16:03 UTC, nbirillo commented on Homework_2/task_2.c
> +                if (random_number_array[i] == user_number_array[j]) {
Может все же `random_numbers`, `user_numbers`?

2020-09-24 16:03 UTC, nbirillo commented on Homework_2/task_2.c
> +        }
Это тоже можно вынести в функцию

2020-09-24 16:12 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +int main()
Забыл убрать в комментарий, это возможность вывода ответа)

2020-09-24 16:13 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +        }
По правилам игры рандомное число должно быть из неповторяющихся чисел

2020-09-24 16:17 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +    int random_number_array[DIGITAL_RANGE];
"В классическом варианте игра рассчитана на двух игроков. Каждый из игроков задумывает и записывает тайное 4-значное число с неповторяющимися цифрами." 
Константа тут, чтобы смотреть не на 4, а на DIGITAL_RANGE, мне показалось, что так понятнее будет осознавать код

2020-09-24 16:31 UTC, nbirillo commented on Homework_2/task_2.c
> +    int random_number_array[DIGITAL_RANGE];
Это понятно :) Но тебе надо научиться работать с динамическими массивами и утечками памяти, поэтому сделай его динамическим

2020-09-24 16:32 UTC, nbirillo commented on Homework_2/task_2.c
> +        }
Я все ещё считаю, что это можно сделать более элегантно, а не проходить каждый раз по массиву заново в поисках этого числа

2020-09-24 16:35 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +    int random_number_array[DIGITAL_RANGE];
Я в той задаче утечку найти не могу, теперь еще 1 
:(

2020-09-24 19:09 UTC, VseslavKasatsky commented
@nbirillo

2020-09-25 06:55 UTC, nbirillo commented on Homework_2/task_2.c
> +    int random_number_array[DIGITAL_RANGE];
Если ты не можешь найти утечку, это не повод не использовать динамические массивы нигде больше :)

![image](https://user-images.githubusercontent.com/8993915/94235995-2813be00-ff15-11ea-8711-26ef97f70595.png)

2020-09-25 13:19 UTC, nbirillo requested changes

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +                // printf("%d", random_number[i]); - answer
Конечный код не должен содержать заккоментированный код

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +            }
Выглядит так, как будто бы ты собирался писать `while` :)

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +    bool isEqual = true;
Если ты используешь эту переменную только внутри вложенного цикла, то там и объявляй

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +void fill_with_random_numbers(int* random_number, int DIGITAL_RANGE)
Все еще выглядит сложно. Попробуй упростить логику, также попробуй сделать код более читабельным. У тебя сейчас такой алгоритм действий:
1. генерировать рандомное число, пока не получим такое, которого еще нет
2. переходим к следующему числу
Это очевидным образом имеет логические части - пройтись по массиву и сгенерировать неповторябщееся число. То есть, если вынести код для генерации уникального значения в отдельный метод, то будет сильно проще читаться. Я имею в виду что-то такое:

функция fill_with_random_numbers:
```
for (int i = 0; i < DIGITAL_RANGE; ++i) {
        random_number[i] = get_unique_number(....)
}
```
ну и собственно отдельная функция, которая будет возвращать уникальное значениет рандомное. Таким образом у тебя будут маленькие логические части, которые легко и приятно читать
При это мне все еще кажется, что необязательно проходить каждый раз по массиву. У тебя же ограниченный набоо чисел. Почему не создать массив bool, в котором проставлять true, если этот элемент уже был сгенерирован и генерировать в таком случае заново? А еще кажется кстати, если у тебя такое ограничение на длину массива, то необязательно использовать `int`, а можно взять что-то и поменьше)

+ наверное все же `random_numbers`, а не `number`

+ `DIGITAL_RANGE` уже не константа, не надо капсом

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +    while (isGuessed) {
Очень странно выглядит - играть _ПОКА УГАДАНО_, переименуй

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +void get_user_guesses(int* user_number, int DIGITAL_RANGE)
Почему множественное число в названии функции? Это же _одно_ предположение.

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +    int* user_number = (int*)malloc(DIGITAL_RANGE * sizeof(int));
Наверное `numbers`? Везде та же ошибка

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +void count_equal_numbers(int* user_number, int* random_number, int* cow,
Все же наверное ты считаешь `bull` и `cow` или еще что-то, а не только одинаковые цифры

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +                    *bull = *bull + 1;
`= `-> `+=`

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +                    *cow = *cow + 1;
`= `-> `+=`

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +                i++;
`i++` :)

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +    printf("YOUR GUESS: ");
Давай все же проверим, что пользователь ввел число нужного количества знаков и если нет, то попросим его ввести заново

2020-09-25 13:19 UTC, nbirillo commented on Homework_2/task_2.c
> +    scanf("%d", &DIGITAL_RANGE);
Добавь проверку на возможное количество, я так понимаю пользователь больше 10 ввести не должен (так как уникальных цифр 10) и меньше нуля или 0 тоже собственно, нижнюю границу можешь выбрать любую, можно например и 4 сделать

2020-09-25 13:39 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +                i++;
?

2020-09-25 13:54 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +void fill_with_random_numbers(int* random_number, int DIGITAL_RANGE)
В рамках тех 3 занятий у нас не поднималась тема использования методов. До этого я их не использовал

2020-09-25 14:25 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +    while (isGuessed) {
![image](https://user-images.githubusercontent.com/71323710/94278865-0554ca00-ff54-11ea-937a-db319a4f398a.png)
Угадывается
Пока угадывается

2020-09-25 14:29 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +            }
Чисто теоретически, просто тут тогда все равно создавать переменную j чтобы сравнивать [i] и [j]

2020-09-25 14:31 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +void fill_with_random_numbers(int* random_number, int DIGITAL_RANGE)
Насчет булевского массива, 
Разве проходить каждый раз по булевскому массиву из 10 чисел не трудозатратнее чем по массиву из 4-10 элементов?

2020-09-25 14:45 UTC, nbirillo commented on Homework_2/task_2.c
> +void fill_with_random_numbers(int* random_number, int DIGITAL_RANGE)
ну теперь то ты их можешь использовать :)))))

2020-09-25 14:45 UTC, nbirillo commented on Homework_2/task_2.c
> +    while (isGuessed) {
Все равно немного кривовато звучит конечно.. ну ладно, ок, давай так оставим

2020-09-25 14:46 UTC, nbirillo commented on Homework_2/task_2.c
> +                i++;
Можно использовать `++i`, это быстрее

2020-09-25 14:47 UTC, nbirillo commented on Homework_2/task_2.c
> +            }
Просто делать цикл for и останавливать его по условию звучит так, как будто бы тебе надо сделать цикл while :) ну либо добавить условие остановки внутрь цикла for

2020-09-25 14:58 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +void fill_with_random_numbers(int* random_number, int DIGITAL_RANGE)
Методы? А что это

2020-09-25 14:59 UTC, samorojy commented on Homework_2/task_2.c
> +void fill_with_random_numbers(int* random_number, int DIGITAL_RANGE)
Это вкратце моё практическое понимание этого

2020-09-25 16:37 UTC, nbirillo commented on Homework_2/task_2.c
> +void fill_with_random_numbers(int* random_number, int DIGITAL_RANGE)
Методы = функции :)))))

2020-09-27 06:47 UTC, nbirillo requested changes
Уже сильно лучше, но все еще есть правки

2020-09-27 06:47 UTC, nbirillo commented on Homework_2/task_2.c
> +int get_unique_number(bool* digitalArray)
Naming (с самим названием все ок, читай правила для именований [тут](https://webkit.org/code-style-guidelines/#names)) 

Ну и в целом коммент - смешивать snake case и camel case очень плохо

2020-09-27 06:47 UTC, nbirillo commented on Homework_2/task_2.c
> +    bool digitalArray[10] = { false };
Все еще хочется, чтобы 10 была константой

2020-09-27 06:47 UTC, nbirillo commented on Homework_2/task_2.c
> +void fill_with_random_numbers(int* random_numbers, int DigitalRange)
Тоже naming + в camel case первая буква у перемнных маленькая - digitalRange

Везде поправь ввобщем его

2020-09-27 06:47 UTC, nbirillo commented on Homework_2/task_2.c
> +            entered_number /= 10; // convert user number to array
Ну кажется, что это делать нужно, если введено только верное количество цифр. Кажется это можно проверить одним if с двойным условием. Каждый раз при неверном вводе пробегать по массиву так себе идея

2020-09-27 06:47 UTC, nbirillo commented on Homework_2/task_2.c
> +        scanf("%d", &entered_number);
Предполагается, что либо ты должен пользователю говорить, что за ошибка случается (что предпочтительнее), либо говорить перед вводом, сколько там должно быть цифр. Иначе не очень понятно, почему он просит вечно заново ввести предположение

2020-09-27 06:47 UTC, nbirillo commented on Homework_2/task_2.c
> +        scanf("%d", &DigitalRange);
Те же комментарии, что и выше - либо говорить, что за ошибка, либо говорить в условии, что требуется (какие есть ограничения)

2020-09-27 09:05 UTC, VseslavKasatsky commented
![image](https://user-images.githubusercontent.com/71323710/94360900-56ca9980-00b9-11eb-819a-d62242fc5e74.png)
В данном случае гитхаб чекер не принимает если использовать bool digital_array[DIGITAL_RANGE] = {false}
Поэтому циклом

2020-09-27 10:13 UTC, nbirillo requested changes
Последние замечания, только проследи, чтобы память не терялась после исправлений

2020-09-27 10:13 UTC, nbirillo commented on Homework_2/task_2.c
> +int get_unique_number(bool* digital_array)
Как говорит [стайлгайд](https://webkit.org/code-style-guidelines/#names) (Егор сказал, что вы используете именно его), нужно использовать camel case. Поэтому начиная с этой задачи попрошу тебя перейти на него (хоть я и сама на плюсах пишу, используя snake case).

2020-09-27 10:13 UTC, nbirillo commented on Homework_2/task_2.c
> +    int* user_numbers = (int*)malloc(digital_range * sizeof(int));
Используй `memset`, чтобы заинициализировать память нулями. То же касается массива с bool - выдели динамически память и проинициализируй нужным значением с помощью `memset` вместо использования цикла

2020-09-27 10:54 UTC, VseslavKasatsky commented
Извините, а может быть у вас найдется сетап настроек для Clion?)
![image](https://user-images.githubusercontent.com/71323710/94363140-e297f200-00c8-11eb-9c59-01befaca90c4.png)

2020-09-28 08:04 UTC, nbirillo commented
Неа, но ты сам можешь их проставить вот тут
![image](https://user-images.githubusercontent.com/8993915/94406146-42020a80-017a-11eb-90b9-f21a0f24e1c9.png)

Ты все поправил и можно смотреть?

2020-09-28 09:06 UTC, VseslavKasatsky commented
@nbirillo Да

2020-09-28 09:56 UTC, nbirillo requested changes
![image](https://user-images.githubusercontent.com/8993915/94418333-ec355e80-0189-11eb-96b8-60f10958ab3a.png)
У тебя не всегда работает считывание ввода пользователя

2020-09-28 09:56 UTC, nbirillo commented on Homework_2/task_2.c
> +    printf("%d", uniqueNumber);
Ты не удалил вывод загаданного числа снова)

2020-09-28 10:30 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +    printf("%d", uniqueNumber);
:(
поправил

2020-09-28 12:05 UTC, VseslavKasatsky commented
@nbirillo 
v.999

2020-09-28 16:58 UTC, nbirillo reviewed
Из-за недочета с char\int будет неполный балл за задачу - 0.9, так как уже прошло 4 ревью. Будь внимательнее в следующий раз

2020-09-28 16:58 UTC, nbirillo commented on Homework_2/task_2.c
> +    char* enteredNumber = (int*)malloc(digitalRange + 2 * sizeof(int));
Ну для массива char делать выделение на int вообще-то неверно

2020-09-28 16:58 UTC, nbirillo commented on Homework_2/task_2.c
> +        while (enteredNumber[digitCount] != '\0') {
И такие штуки лучше в константы выносить `'\0'`, но в целом так тоже ок

2020-09-28 16:58 UTC, merged

2020-09-28 17:01 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +    char* enteredNumber = (int*)malloc(digitalRange + 2 * sizeof(int));
Я забыл удалить прошлую переменную

2020-09-28 17:02 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +    char* enteredNumber = (int*)malloc(digitalRange + 2 * sizeof(int));
:(

2020-09-28 17:05 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +    char* enteredNumber = (int*)malloc(digitalRange + 2 * sizeof(int));
можно ненада

2020-09-28 17:08 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +    char* enteredNumber = (int*)malloc(digitalRange + 2 * sizeof(int));
@nbirillo Можно ли простить данный недочет т.к первым сдал задачу?

2020-09-28 17:51 UTC, nbirillo commented on Homework_2/task_2.c
> +    char* enteredNumber = (int*)malloc(digitalRange + 2 * sizeof(int));
В следующий раз будешь аккуратнее :) 
![image](https://user-images.githubusercontent.com/8993915/94467927-4ce58b00-01cc-11eb-89b4-48d25edf14f2.png)

2020-09-28 18:14 UTC, VseslavKasatsky commented on Homework_2/task_2.c
> +    char* enteredNumber = (int*)malloc(digitalRange + 2 * sizeof(int));
@nbirillo 
![39a6b4b3319196a5f98a486e200bd3e4](https://user-images.githubusercontent.com/71323710/94469905-879cf280-01cf-11eb-85f4-5ea10d2abbed.jpg)