20.Б10-мм, Касацкий.В, 2.1
VseslavKasatsky/spbu_2020_c_homeworks pull request #6
Opened 2020-09-21 23:10 UTC by VseslavKasatsky

@SpirinEgor

2020-09-22 20:41 UTC, nbirillo requested changes
Добавь, пожалуйста, автоматическую проверку стайлгайда

2020-09-22 20:41 UTC, nbirillo commented on Homework_2/task_1.c
> +int* values = NULL;
Не используй глобальные переменные

2020-09-22 20:41 UTC, nbirillo commented on Homework_2/task_1.c
> +	scanf("%d", &number);
Добавь описание для пользователя, что ему надо вводить и что он получит

2020-09-22 20:41 UTC, nbirillo commented on Homework_2/task_1.c
> +void print()
Используй более говорящие названия - `print` что?

2020-09-22 20:41 UTC, nbirillo commented on Homework_2/task_1.c
> +	for (int i = 1; i < size; i++)
Все та же разница между` i++` и `++i `:)

2020-09-22 20:41 UTC, nbirillo commented on Homework_2/task_1.c
> +void recursion(int left_sum, int last_term)
Поменяй имя на что-то более говорящие. Оно должно быть таким, чтобы ты посмотрел на название и понял, что будет происходить. Сейчас ты можешь понять, что там какая-то рекурсия и ничего больше :)

2020-09-22 20:41 UTC, nbirillo commented on Homework_2/task_1.c
> +		values = array;
А зачем тебе нужен `array`, если ты сразу же перезаписываешь это в `values` и нигде потом не используешь `array`?

2020-09-23 08:52 UTC, nbirillo requested changes
Запусти с волгриндом и поправь утечки, они появились после исправлений

2020-09-23 08:52 UTC, nbirillo commented on Homework_2/task_1.c
> +void print_answer_to_console(int size, int* values)
Все еще не говорящее название - представь, что ты впервые видишь этот код (и часть это не какие-то маленькие задачки, а проекты). Ты читаешь код и там название "напечатать ответ в консоль". И пока ты не посмотришь ВСЮ реализацию - ты не поймешь какой _ответ_ печатается то. Обычно хорошо называть что-то типа `print_permutation`, `print_decomposed_number` - по таким названиям ты интуитивно можешь понять, что происходит внутри функции, не читая ее тело

2020-09-23 08:52 UTC, nbirillo commented on Homework_2/task_1.c
> +void decomposition_of_number(int left_sum, int last_term, int size, int* values)
Давай лучше называть методы, начиная с глагола - если он совершает действие. Например, `decompose_number`. 

На будуее - Если, например, это какая-то проверка, то можно использовать `is` и называть что-то типа `isEqual` и тд

Так сильно проще читается. Но уже сильно лучше, так как хотя бы понятно, чего ожидать внутри функции

2020-09-23 11:31 UTC, VseslavKasatsky commented on Homework_2/task_1.c
> +void print_answer_to_console(int size, int* values)
Valgrind'a получается для windows нет? 
Утечка где-то в realloc? Как ее можно поправить ?

2020-09-23 15:54 UTC, nbirillo commented on Homework_2/task_1.c
> +void print_answer_to_console(int size, int* values)
Для windows нет, да. Но есть альтернативы. Посмотри вот в эту сторону:
1. https://drmemory.org/ - довольно старый, но вроде неплох и хватит для наших задач
2. если что-то более новое, то почитай [тут](https://devblogs.microsoft.com/cppblog/addresssanitizer-asan-for-windows-with-msvc/) 
3. если использовать clang, то есть встроенная (в виде расширение) в стандартную библиотеку дебаг-библиотека, см. функцию [_CrtSetDbgFlag](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/crtsetdbgflag?view=vs-2019), флаг тебе нужен `_CRTDBG_LEAK_CHECK_DF`

Разбирайся с этим или ставь себе линкус :) А как исправить - придется подумать самому. Главное правило - выделил память, освободи ее.

2020-09-23 19:09 UTC, nbirillo commented on Homework_2/task_1.c
> +void print_answer_to_console(int size, int* values)
И еще поправь конфликты и тесты :) и убери файлик со стилями

2020-09-23 20:58 UTC, VseslavKasatsky commented on Homework_2/task_1.c
> +void print_answer_to_console(int size, int* values)
Утечку памяти бы починить ((
Конфликты-тесты-стили поправлю

2020-09-24 19:21 UTC, VseslavKasatsky commented on Homework_2/task_1.c
> +void print_answer_to_console(int size, int* values)
Можно какую-нибудь подсказку для починки?

2020-09-25 06:57 UTC, nbirillo commented on Homework_2/task_1.c
> +void print_answer_to_console(int size, int* values)
У тебя `decompose_number` - рекурсивная функция. В ней ты выделяешь память. Как она работает? Сколько раз по-твоему будет выделена память? Совпадает ли это количество с вызовом `free`?

2020-09-25 07:49 UTC, nbirillo commented on Homework_2/task_1.c
> +void print_answer_to_console(int size, int* values)
Конкретно сейчас у тебя в принципе программа перестала запускаться с valgrind
![image](https://user-images.githubusercontent.com/8993915/94240956-af186480-ff1c-11ea-813c-14cf666e0910.png)

Нужно читать логи и искать ошибку, я этим заниматься точно не буду :) Ты поставил себе что-то вместо него?

2020-09-27 10:56 UTC, VseslavKasatsky commented
@nbirillo

2020-09-28 08:07 UTC, nbirillo approved these changes
Отлично, зачтено!

2020-09-28 08:07 UTC, merged