20.Б10-мм, Касацкий В., Лист
VseslavKasatsky/spbu_2020_c_homeworks pull request #7
Opened 2020-09-30 14:24 UTC by VseslavKasatsky

2020-10-07 22:45 UTC, VseslavKasatsky commented
@SokolovYaroslav

2020-10-09 18:26 UTC, SokolovYaroslav requested changes
Явно не написал, напишу тут: 1-индексация это зло, я чуть голову не сломал. Надо переписать на 0-индексацию.

А ещё когда пишут код, его обычно разбивают на смысловые блоки переносами строк. Полотно текста подряд выглядит страшно. Тоже надо исправить.

Ну и по остальным замечаниям тоже.

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.h
> +#include <stdbool.h>
Ну, инклуды должны быть в начале всё-таки. После стражей то есть.

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.h
> +#endif // SPBU_2020_C_HOMEWORKS_LIBRARY_commonUtils_LIST_H_
Отступы бы какие-нибудь, чтобы смысловые блоки разделить :)

2020-10-09 18:26 UTC, SokolovYaroslav commented on Homework_3/task_1.c
> +    delete (3, numbers);
Пробельчик явно лишний

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    free(temp);
То есть ты хочешь сделать `free(NULL)`?

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        delete (1, list);
И тут пробельчик. Как так вышло, что оба раза именно после `delete`'а?

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position > getSize(list) || position < 1) {
То есть здесь 1-индексация? Ну это очень не очевидно и вообще так нельзя.

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        free(list->head);
По идее должна быть отдельная функция, которая удаляет `ListElement `.  И удалять стоит только через неё, потому что иначе есть шанс случайно дважды что-то удалить.

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        free(list->head);
Это относится почти ко всем `free` в твоём коде

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    ListElement* temp = head(list);
Можно вместо абстрактного `temp` придумать что-то более информативное. Например, `to_print`

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    ListElement* temp = head(list);
Это относится почти ко всем `temp`. Исключение в голову приходит только одно: функция `swap`.

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    return temp->previous->value;
Ожидаем указатель, получаем `int`.

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position > getSize(list)) {
Отрицательный и должен проходить?

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    return temp->previous->value;
Вообще, такие вещи нормальная IDE подсвечивает.

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position > getSize(list) + 1) {
Тоже самое про отрицательность

2020-10-09 18:26 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +            list->tail = element->next;
Но зачем...
Там ведь уже и так стоит тот элемент.

2020-10-09 18:26 UTC, SokolovYaroslav commented on CMakeLists.txt
> +add_executable(2.task_4 Homework_2/2.task_4.c)
Чет тут лишние вставки и удаления. Надо убрать

2020-10-09 20:24 UTC, SokolovYaroslav commented
Я там отписал Дягтереву, напишу и сюда. Чет мне кажется, что либо ты списал, либо вы делали эту домашку вдвоем. Обе ситуации -- это плохо.

Сейчас это прям явно видно. Если в будущем будут хотя бы подозрения, то я поставлю 0 обоим.

2020-10-09 20:35 UTC, VseslavKasatsky commented
@SokolovYaroslav часть всего этого мы писали в классе

2020-10-09 20:41 UTC, VseslavKasatsky commented on Homework_3/task_1.c
> +    delete (3, numbers);
Я могу ошибаться, но вроде такой styleGuide
![image](https://user-images.githubusercontent.com/71323710/95629583-e47a9180-0a88-11eb-89f2-6d208f328343.png)

2020-10-09 20:43 UTC, SokolovYaroslav commented on Homework_3/task_1.c
> +    delete (3, numbers);
Я про пробельчик после `delete`

2020-10-09 20:45 UTC, SokolovYaroslav commented
А. ок, зря быканул

2020-10-09 20:47 UTC, VseslavKasatsky commented on Homework_3/task_1.c
> +    delete (3, numbers);
Согласен

2020-10-09 20:49 UTC, VseslavKasatsky commented on library/commonUtils/list.h
> +#endif // SPBU_2020_C_HOMEWORKS_LIBRARY_commonUtils_LIST_H_
Отступы между чем и чем? Между смысловым блоком функций?

2020-10-09 20:54 UTC, VseslavKasatsky commented on library/commonUtils/list.c
> +        delete (1, list);
Clion почему-то решил так сделать :(
поправлю

2020-10-09 20:56 UTC, VseslavKasatsky commented on CMakeLists.txt
> +add_executable(2.task_4 Homework_2/2.task_4.c)
Эту строчку я просто переместил ниже, чтобы стояли по порядку
2.task_3
2.task_4 и тд

2020-10-09 21:10 UTC, VseslavKasatsky commented on library/commonUtils/list.c
> +        delete (1, list);
![image](https://user-images.githubusercontent.com/71323710/95631790-f1997f80-0a8c-11eb-96bd-00569a821482.png)
наверное из-за магического названия delete

2020-10-10 09:49 UTC, SokolovYaroslav commented
Коммит месседжи жесть! :)
Сейчас спрошу, надо вас за такое карать или нет

2020-10-10 10:01 UTC, SokolovYaroslav requested changes
Ну кроме багулины всё норм почти

2020-10-10 10:01 UTC, SokolovYaroslav commented on library/commonUtils/list.h
> +#endif // SPBU_2020_C_HOMEWORKS_LIBRARY_commonUtils_LIST_H_
Теперь опрятнее, но логики разделения на блоки я не до конца улавливаю :)
Но это уже ладно, пофиг

2020-10-10 10:01 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    return position;
А если нет такого элемента?

2020-10-10 10:01 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position > getSize(list) || position < 0) {
Ну вот если попробовать удалить элемент на позиции `getSize(list)`, то всё падает

2020-10-10 10:07 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +}
А какая логика у отступов между функциями? Где-то есть, где-то нет

2020-10-10 10:08 UTC, VseslavKasatsky commented on library/commonUtils/list.c
> +}
Ну не знаю, думал как можно блоки сделать 
Ну если убрать я думаю читабельность не потеряется, но будет единый вид

2020-10-10 12:07 UTC, SokolovYaroslav requested changes

2020-10-10 12:07 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        return false;
Не лучшее решение, но лучшее решение не подходит по интерфейсу.
В идеале, видимо, надо в отдельную перменную, которую передают в функцию, класть код ошибки.

2020-10-10 12:07 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position > getSize(list) - 1 || position < 0 || getSize(list) < 0) {
В одном месте `>=`, а в другом `> x - 1`

2020-10-10 12:07 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        return false;
Ну да, раз не подходит, то исправлять это не обязательно.

2020-10-11 08:42 UTC, SokolovYaroslav approved these changes

2020-10-11 09:18 UTC, VseslavKasatsky commented
@SokolovYaroslav мердж Егор сделает ?

2020-10-11 09:26 UTC, SokolovYaroslav commented
Щас я разберусь какой порядок действий и вмерджу

2020-10-11 10:51 UTC, merged

2020-10-11 10:56 UTC, VseslavKasatsky commented
@SokolovYaroslav вверху "таблички" пишется сколько баллов за каждую задачу ставится

2020-10-11 11:00 UTC, SokolovYaroslav commented
Спс