20.Б10-мм, Касацкий.В, 3.2
VseslavKasatsky/spbu_2020_c_homeworks pull request #8
Opened 2020-10-02 23:42 UTC by VseslavKasatsky

2020-10-07 22:45 UTC, VseslavKasatsky commented
@SokolovYaroslav

2020-10-09 19:53 UTC, SokolovYaroslav requested changes
В задании написано, что нужно переиспользовать лист из прошлого задания.

2020-10-09 19:53 UTC, SokolovYaroslav commented on CMakeLists.txt
> +add_executable(3.task_2 Homework_3/task_2.c library/commonUtils/cycleList.c)
Снова куча лишнего

2020-10-09 19:53 UTC, SokolovYaroslav commented on Homework_3/task_2.c
> +    int numberOfSoldiers = 0, killRatio = 0;
Предлагаю писать в отдельных строках-таки

2020-10-09 21:40 UTC, VseslavKasatsky commented on CMakeLists.txt
> +add_executable(3.task_2 Homework_3/task_2.c library/commonUtils/cycleList.c)
То, что выше - от прошлых дз, когда это все будет в 1 ветке, то можно будет запустить любую ДЗ-шку

2020-10-09 21:41 UTC, samorojy commented
@SokolovYaroslav в тот момент мне показалось, что проще переписать библиотеку, в принципе ничего не поменялось в плане реализации функций, но стало более удобнее в использовании. 
Таким образом, библиотека list и cycleList примерно одинаковы, просто в list'e нет нагромождения функций для циклического и поэтому удобнее работать, поэтому я считаю, что задача выполнена

2020-10-09 21:58 UTC, samorojy commented
Ну и в дальнейшем библиотека с циклическим листом будет полезна

2020-10-10 10:11 UTC, SokolovYaroslav commented on CMakeLists.txt
> +add_executable(3.task_2 Homework_3/task_2.c library/commonUtils/cycleList.c)
Ну это здорово, но почему это в этом PRе?

2020-10-10 10:13 UTC, SokolovYaroslav commented
> просто в list'e нет нагромождения функций для циклического и поэтому удобнее работать
Ну так его и не появится. Я ожидал, что циклический лист будет обёрткой над обычным листом и там будет переиспользование всех функций, которые по твоим же словам, особо не поменялись бы.

2020-10-10 10:22 UTC, VseslavKasatsky commented
@SokolovYaroslav ок
Можно тогда через этот пулреквест эту библиотеку все же добавить? 
А алгоритм через list.c я переделаю

2020-10-10 10:27 UTC, SokolovYaroslav commented
Не догоняю.
Я не прошу делать алгоритм с помощью list.c
Я прошу сделать cycleList.c через list.c

2020-10-10 16:52 UTC, VseslavKasatsky commented
@SokolovYaroslav поменял все
Может быть я чего-то не понимаю, но ветку создавал от task_1 и значит изменения в ней должны отражаться тут, почему-то не так...Поэтому для мерджа обновил в этой ветки файлы task1,list.c,list.h. Когда вы смерджите 1 ветку, то в этой не будет конфликта

2020-10-11 08:47 UTC, SokolovYaroslav commented
А ты мерджил в эту ветку ветку 3.1 после того, как обновлял 3.1?
Вроде нет, судя по коммитам. Поэтому и не отображаются изменения.

2020-10-11 09:16 UTC, VseslavKasatsky commented
@SokolovYaroslav мне казалось, что если начинаешь новую ветку от другой, то при изменениях старой она будет автоматически изменяться (как это при изменении мастера)

2020-10-11 09:23 UTC, SokolovYaroslav commented
Так, снова по поводу переиспользования.
Нужно переиспользовать list.c так, чтобы не знать, что там написано. То есть нужно заимпортить list.h и пользоваться всеми функциями обычного листа исключительно через этот интерфейс!
Вот так же, как ты пользуешься библиотекой в task_*.c

То есть условно ты должен реализовать блиблиотеку циклического листа, ничего не зная о том, что написано в list.c. Копипаста кода из list.c означает, что ты знаешь, что там написано.
Кароч попробуй сделать вид, что list.c вообще не твой файл и смотреть его никак нельзя.

2020-10-11 09:24 UTC, SokolovYaroslav commented
По поводу изменений ветки: нет само не изменяется. При изменении мастера также надо постоянно подтягивать мастер в свою текущую ветку.

2020-10-11 09:30 UTC, SokolovYaroslav requested changes
Попытка переиспользовать list.c номер 2

2020-10-11 09:30 UTC, VseslavKasatsky commented
@SokolovYaroslav Т.е чтобы интерфейс был такой же, а вот реализацию функций я могу сделать любой?

2020-10-11 09:34 UTC, SokolovYaroslav commented
Если правильно понял, то нет.
Ща

2020-10-11 09:38 UTC, SokolovYaroslav commented
Ну вот смотри. 
Ты хочешь сделать условный `CycleList`. Для этого ты делаешь структурку, в которой лежит например обычный лист (если просто обычный не подходит) и что-то еще.
Потом ты хочешь условную функцию `insertToCycleList`. Для этого ты берешь обычный лист из своей структурки `CycleList`, как-то преобразовываешь входной индекс и передаешь его и новый элемент в `insert` обычного листа.

Дальше по аналогии.
Для этого

2020-10-11 09:39 UTC, SokolovYaroslav commented
То есть по сути библиотека `cycleList` будет заниматься только тем, что специальным образом обрабатывать входы и передавать их обычному листу.

2020-10-11 09:44 UTC, SokolovYaroslav commented
Можешь глянуть, как у Дягтерева сделано например

2020-10-14 10:50 UTC, VseslavKasatsky commented
@SokolovYaroslav

2020-10-17 18:11 UTC, SokolovYaroslav requested changes

2020-10-17 18:11 UTC, SokolovYaroslav commented on CMakeLists.txt
> +add_executable(3.task_2 Homework_3/task_2.c library/commonUtils/list.c)
Мне тут рассказали, что надо либу не так добавлять в executable.
У Анны Кропачевой сделано правильно, можешь глянуть

С 3.1 надо тоже переделать

2020-10-17 18:11 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +ListElement* nextElement(List* list, ListElement* previousElement)
В названии не отражена цикличная логика.

2020-10-17 18:20 UTC, VseslavKasatsky commented on CMakeLists.txt
> +add_executable(3.task_2 Homework_3/task_2.c library/commonUtils/list.c)
Егор почему-то не сердился на такое...

2020-10-17 18:25 UTC, SokolovYaroslav commented on CMakeLists.txt
> +add_executable(3.task_2 Homework_3/task_2.c library/commonUtils/list.c)
Это он мне сказал, что я твою 3.1 пропустил с такой дичью

2020-10-17 18:45 UTC, SokolovYaroslav requested changes

2020-10-17 18:45 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +ListElement* getNextElement(List* list, ListElement* previousElement)
Так ведь снова не ясно, что тут по циклу следующий элемент берётся

2020-10-17 18:48 UTC, VseslavKasatsky commented on library/commonUtils/list.c
> +ListElement* getNextElement(List* list, ListElement* previousElement)
getNextCurrentElement ? 
получить следующий после текущего элемента

2020-10-17 18:50 UTC, VseslavKasatsky commented on library/commonUtils/list.c
> +ListElement* getNextElement(List* list, ListElement* previousElement)
или
getTheNextOneAfterTheCurrentElement

2020-10-17 18:57 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +ListElement* getNextElement(List* list, ListElement* previousElement)
getNextInCycle мб, хз

2020-10-17 18:57 UTC, VseslavKasatsky commented on library/commonUtils/list.c
> +ListElement* getNextElement(List* list, ListElement* previousElement)
Просто тут же лист не только для цикла...

2020-10-17 19:00 UTC, merged

2020-10-17 19:06 UTC, VseslavKasatsky commented
@SokolovYaroslav почему 1 балл? Конечно, дедлайн прошел, но пуллреквест создан 2 числа, время от 1 проверки до сегодняшнего дня - 8 дней. Т.е я бы вложился в дедлайн...

2020-10-17 19:34 UTC, SokolovYaroslav commented
> @SokolovYaroslav почему 1 балл? Конечно, дедлайн прошел, но пуллреквест создан 2 числа, время от 1 проверки до сегодняшнего дня - 8 дней. Т.е я бы вложился в дедлайн...

5 дней назад первое удовлетворительное решение появилось