20.Б10-мм. Касацкий.В, тест1.1
VseslavKasatsky/spbu_2020_c_homeworks pull request #9
Opened 2020-10-13 09:12 UTC by VseslavKasatsky

2020-10-13 10:35 UTC, VseslavKasatsky commented
Знаю, что можно было гораздо более эффективнее "сложить" 2 массива, но не успевал отдебажить вариант поочередного добавления элементов.

2020-11-05 12:18 UTC, SpirinEgor requested changes

2020-11-05 12:18 UTC, SpirinEgor commented on Test/task_1.c
> +    int* petyaSummary = malloc(subjects * sizeof(int));
Вижу малоки, но не вижу освобождения памяти

2020-11-05 12:18 UTC, SpirinEgor commented on Test/task_1.c
> +    printf("Enter Petya summary with %d elements", subjects);
В общем случае число предметов у ребят может различаться

2020-11-05 12:18 UTC, SpirinEgor commented on Test/task_1.c
> +    qsort(summary, 2 * subjects, sizeof(int), arraySort);
К сожалению, в задании требовалось именно эффективно сделать. Так что такой вариант не могу засчитать.
Надо было написать слияние за O(n), у тебя сортировка за O(nlogn).

2020-11-05 12:18 UTC, SpirinEgor approved these changes

2020-11-05 12:20 UTC, merged

2020-11-05 13:03 UTC, VseslavKasatsky commented on Test/task_1.c
> +    qsort(summary, 2 * subjects, sizeof(int), arraySort);
Тогда будет ли возможность переписать такой номер?

2020-11-05 13:42 UTC, SpirinEgor commented on Test/task_1.c
> +    qsort(summary, 2 * subjects, sizeof(int), arraySort);
Будет переписывание, там будут новые, но похожие задачи. Тебе получается только 1 надо будет решить.